package chat_tcp;

import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 2200593@ifto.local
 */
public class TelaCliente extends javax.swing.JFrame {
    Cliente cliente;
    TelaChat telaChat;
    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() {
        initComponents();
        icone.setIcon(new ImageIcon("cliente.png"));
        icone.setText("");   
        //telaChat.setVisible(false);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        porta = new javax.swing.JTextField();
        ip = new javax.swing.JTextField();
        icone = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setText("Nome de Usuário:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 270, 120, 19);
        getContentPane().add(login);
        login.setBounds(220, 270, 110, 25);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 310, 72, 25);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 310, 83, 25);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Servidor"));
        jPanel1.setLayout(null);

        jLabel1.setText("Porta:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 30, 44, 19);

        jLabel2.setText("Endereço IP:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 70, 79, 19);
        jPanel1.add(porta);
        porta.setBounds(110, 30, 100, 25);
        jPanel1.add(ip);
        ip.setBounds(120, 70, 90, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(90, 140, 240, 110);

        icone.setText(".");
        getContentPane().add(icone);
        icone.setBounds(170, 30, 100, 100);

        setBounds(0, 0, 400, 396);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        try {
            
            int port = Integer.parseInt(porta.getText());
            Usuario usuario = new Usuario(port,ip.getText(),login.getText());
            cliente = new Cliente(usuario);
            
            cliente.conectar();
            JOptionPane.showMessageDialog(null, "Cliente Conectado!");
                
            telaChat = new TelaChat(this,true,cliente);
            telaChat.setVisible(true);  
            
        } catch (IOException ex) {
             JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icone;
    private javax.swing.JTextField ip;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField login;
    private javax.swing.JTextField porta;
    // End of variables declaration//GEN-END:variables
}
