package chat_tcp;

import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


import javax.swing.text.Document;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 2200593@ifto.local
 */
public class TelaCliente extends javax.swing.JFrame {
    Cliente cliente;
    TelaChat telaChat;
    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() {
        initComponents();
        icone.setIcon(new ImageIcon("cliente.png"));
        icone.setText("");   
        //telaChat.setVisible(false); 
        
        /*
        initComponents();
        //icone.setIcon(new ImageIcon("/assets/cliente/usuarioLogin.png"));
        //icone.setText("");   
        //telaChat.setVisible(false);
        
        ImageIcon icone = new ImageIcon("assets/cliente/usuarioLogin.png");
        icone.setImage(icone.getImage().getScaledInstance(jLabel_iconLogin.getWidth(), jLabel_iconLogin.getHeight(),1)); //.setImage(icone.getImage().getScaledInstance(label_logo.getWidth(), label_logo.getHeight(),1));
        jLabel_iconLogin.setIcon(icone);
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        porta = new javax.swing.JTextField();
        ip = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        icone = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 320, 100, 30);

        jButton2.setBackground(new java.awt.Color(249, 119, 119));
        jButton2.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setMaximumSize(new java.awt.Dimension(61, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(61, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 310, 100, 29);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Servidor"));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setText("Porta:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 70, 44, 20);

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setText("Endereço IP:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 40, 90, 20);
        jPanel1.add(porta);
        porta.setBounds(150, 70, 120, 25);
        jPanel1.add(ip);
        ip.setBounds(150, 40, 120, 25);

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setText("Nome do Usuário:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 100, 130, 20);
        jPanel1.add(login);
        login.setBounds(150, 100, 120, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 130, 300, 140);

        icone.setText(".");
        getContentPane().add(icone);
        icone.setBounds(160, 20, 100, 100);

        setBounds(0, 0, 400, 396);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        try {
            
            int port = Integer.parseInt(porta.getText());
            Usuario usuario = new Usuario(port,ip.getText(),login.getText());
            cliente = new Cliente(usuario);
            
            cliente.conectar();
            JOptionPane.showMessageDialog(null, "Cliente Conectado!");
                
            telaChat = new TelaChat(this,true,cliente);
            telaChat.setVisible(true);  
            
        } catch (IOException ex) {
             JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icone;
    private javax.swing.JTextField ip;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField login;
    private javax.swing.JTextField porta;
    // End of variables declaration//GEN-END:variables
}
